### ISSUE TITLE
gsii model cannot be downloaded

### ISSUE THREAD

**Issue by NyistMilan** [plandes/calamr#3]
When trying to use multiple commands I encounter this error:

```
zensols.install.InstallError: Could not install 'model_stog: https://p-def8.pcloud.com/cBZLUUPPBZBfnwosZZZ04jaykZ2ZZzA5ZkZYRHagZO8ZizZG8ZF8Zj8Zy8ZzpZNzZLQZ84Z5LZd4Z6LZn8ZD2z0XZvPD2HM0ahQSA6dLPFYDi8uFiU33y/model_parse_gsii-v0_1_0.tar.gz' in path '/home/nyistmilan/.cache/zensols/amr/gsii-v0_1_0/model_stog': Could not access 'https://p-def8.pcloud.com/cBZLUUPPBZBfnwosZZZ04jaykZ2ZZzA5ZkZYRHagZO8ZizZG8ZF8Zj8Zy8ZzpZNzZLQZ84Z5LZd4Z6LZn8ZD2z0XZvPD2HM0ahQSA6dLPFYDi8uFiU33y/model_parse_gsii-v0_1_0.tar.gz': HTTP Error 410: Gone
```

Could be due to changed url: https://github.com/bjascob/amrlib-models?tab=readme-ov-file#sentence-to-graph-models

**Comment by plandes** [comment]
You're the first to use any of these research specific libraries, so unfortunately, you're finding issues that have to be ironed out in a new environment.

However, this one I can't help with.  Because the Gsii model is distributed on a site that changes dynamically, you have to install it yourself.

However, I have now added [documentation](https://github.com/plandes/calamr#installing), which forwards you to [here](https://github.com/plandes/amr#installing-the-gsii-model).
